In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/European_Bank.csv")
print("Shape:", df.shape)
df.head()

Shape: (10000, 14)

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [3]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
Year               0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Duplicate rows: 0

In [4]:
df.dtypes

Year                 int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [5]:
df.nunique()

Year                   1
CustomerId         10000
Surname             2932
CreditScore          460
Geography              3
Gender                 2
Age                   70
Tenure                11
Balance             6382
NumOfProducts          4
HasCrCard              2
IsActiveMember         2
EstimatedSalary     9999
Exited                 2
dtype: int64

In [6]:
df_clean = df.drop(
    columns=["Year", "CustomerId", "Surname"]
).copy()

df_clean.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
print("Original shape:", df.shape)
print("Clean shape:", df_clean.shape)

Original shape: (10000, 14)
Clean shape: (10000, 11)

In [9]:
def age_group(age):
    if age < 30:
        return "<30"
    elif age <= 45:
        return "30-45"
    elif age <= 60:
        return "46-60"
    else:
        return "60+"

df_clean["AgeGroup"] = df_clean["Age"].apply(age_group)

df_clean["AgeGroup"].value_counts().sort_index()

AgeGroup
30-45    6248
46-60    1647
60+       464
<30      1641
Name: count, dtype: int64

In [11]:
df_clean["CreditScoreBand"] = pd.cut(
    df_clean["CreditScore"],
    bins=[-np.inf, 584, 718, np.inf],
    labels=["Low", "Medium", "High"]
)
df_clean["CreditScoreBand"].value_counts().sort_index()

CreditScoreBand
Low       2534
Medium    5003
High      2463
Name: count, dtype: int64

In [12]:
df_clean["CreditScoreBand"].isna().sum()

np.int64(0)

In [13]:
def tenure_group(tenure):
    if tenure <= 3:
        return "New"
    elif tenure <= 7:
        return "Mid-term"
    else:
        return "Long-term"

df_clean["TenureGroup"] = df_clean["Tenure"].apply(tenure_group)
df_clean["TenureGroup"].value_counts()

TenureGroup
Mid-term     3996
New          3505
Long-term    2499
Name: count, dtype: int64

In [14]:
df_clean["TenureGroup"].isna().sum()

np.int64(0)

In [15]:
def balance_segment(balance):
    if balance == 0:
        return "Zero-balance"
    elif balance <= 97198.54:
        return "Low-balance"
    else:
        return "High-balance"

df_clean["BalanceSegment"] = df_clean["Balance"].apply(balance_segment)
df_clean["BalanceSegment"].value_counts()

BalanceSegment
High-balance    5000
Zero-balance    3617
Low-balance     1383
Name: count, dtype: int64

In [16]:
df_clean["BalanceSegment"].isna().sum()

np.int64(0)

In [17]:
df_clean["EngagementStatus"] = df_clean["IsActiveMember"].map({
    0: "Inactive",
    1: "Active"
})
df_clean["EngagementStatus"].value_counts()

EngagementStatus
Active      5151
Inactive    4849
Name: count, dtype: int64

In [18]:
df_clean["EngagementStatus"].isna().sum()

np.int64(0)

In [19]:
print("Shape:", df_clean.shape)

print("\nColumns:")
print(df_clean.columns.tolist())

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate rows:", df_clean.duplicated().sum())

Shape: (10000, 16)

Columns:
['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'AgeGroup', 'CreditScoreBand', 'TenureGroup', 'BalanceSegment', 'EngagementStatus']

Missing values:
CreditScore         0
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
NumOfProducts       0
HasCrCard           0
IsActiveMember      0
EstimatedSalary     0
Exited              0
AgeGroup            0
CreditScoreBand     0
TenureGroup         0
BalanceSegment      0
EngagementStatus    0
dtype: int64

Duplicate rows: 0

In [20]:
print(df_clean["Exited"].value_counts())
print("\nChurn rate:", df_clean["Exited"].mean() * 100)

Exited
0    7963
1    2037
Name: count, dtype: int64

Churn rate: 20.369999999999997

In [21]:
df_clean.to_csv("../data/European_Bank_Processed.csv", index=False)

print("Processed dataset saved successfully.")
print("Shape:", df_clean.shape)

Processed dataset saved successfully.
Shape: (10000, 16)