In [6]:
import pandas as pd

df = pd.read_csv("../data/European_Bank_Processed.csv")

df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,AgeGroup,CreditScoreBand,TenureGroup,BalanceSegment,EngagementStatus
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,30-45,Medium,New,Zero-balance,Active
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,30-45,Medium,New,Low-balance,Active
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,30-45,Low,Long-term,High-balance,Inactive
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,30-45,Medium,New,Zero-balance,Inactive
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,30-45,High,New,High-balance,Active

In [7]:
total_customers = len(df)
churned_customers = df["Exited"].sum()
retained_customers = total_customers - churned_customers

overall_churn_rate = churned_customers / total_customers * 100
retention_rate = retained_customers / total_customers * 100

print("Total Customers :", total_customers)
print("Churned Customers:", churned_customers)
print("Retained Customers:", retained_customers)
print("Overall Churn Rate:", round(overall_churn_rate, 2), "%")
print("Retention Rate    :", round(retention_rate, 2), "%")

Total Customers : 10000
Churned Customers: 2037
Retained Customers: 7963
Overall Churn Rate: 20.37 %
Retention Rate    : 79.63 %

In [8]:
geography_churn = (
    df.groupby("Geography")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

geography_churn["ChurnRate"] = geography_churn["mean"] * 100

geography_churn["ChurnContribution"] = (
    geography_churn["sum"] / churned_customers * 100
)

geography_churn = geography_churn.drop(columns="mean")

geography_churn

  Geography  count  sum  ChurnRate  ChurnContribution
0    France   5014  810  16.154767          39.764359
1   Germany   2509  814  32.443204          39.960727
2     Spain   2477  413  16.673395          20.274914

In [9]:
age_churn = (
    df.groupby("AgeGroup")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

age_churn["ChurnRate"] = age_churn["mean"] * 100

age_churn["ChurnContribution"] = (
    age_churn["sum"] / churned_customers * 100
)

age_churn = age_churn.drop(columns="mean")

age_churn

  AgeGroup  count  sum  ChurnRate  ChurnContribution
0    30-45   6248  956  15.300896          46.931762
1    46-60   1647  842  51.123254          41.335297
2      60+    464  115  24.784483           5.645557
3      <30   1641  124   7.556368           6.087383

In [10]:
credit_churn = (
    df.groupby("CreditScoreBand")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

credit_churn["ChurnRate"] = credit_churn["mean"] * 100

credit_churn["ChurnContribution"] = (
    credit_churn["sum"] / churned_customers * 100
)

credit_churn = credit_churn.drop(columns="mean")

credit_churn

  CreditScoreBand  count  sum  ChurnRate  ChurnContribution
0            High   2463  500  20.300447          24.545901
1             Low   2534  556  21.941594          27.295042
2          Medium   5003  981  19.608235          48.159057

In [11]:
tenure_churn = (
    df.groupby("TenureGroup")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

tenure_churn["ChurnRate"] = tenure_churn["mean"] * 100

tenure_churn["ChurnContribution"] = (
    tenure_churn["sum"] / churned_customers * 100
)

tenure_churn = tenure_churn.drop(columns="mean")

tenure_churn

  TenureGroup  count  sum  ChurnRate  ChurnContribution
0   Long-term   2499  511  20.448179          25.085911
1    Mid-term   3996  785  19.644645          38.537064
2         New   3505  741  21.141227          36.377025

In [12]:
balance_churn = (
    df.groupby("BalanceSegment")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

balance_churn["ChurnRate"] = balance_churn["mean"] * 100

balance_churn["ChurnContribution"] = (
    balance_churn["sum"] / churned_customers * 100
)

balance_churn = balance_churn.drop(columns="mean")

balance_churn

  BalanceSegment  count   sum  ChurnRate  ChurnContribution
0   High-balance   5000  1249  24.980000          61.315660
1    Low-balance   1383   288  20.824295          14.138439
2   Zero-balance   3617   500  13.823611          24.545901

In [13]:
profile_comparison = (
    df.groupby("Exited")[
        ["CreditScore", "Age", "Tenure",
         "Balance", "NumOfProducts", "EstimatedSalary"]
    ]
    .mean()
    .round(2)
)

profile_comparison.index = ["Retained", "Churned"]

profile_comparison

          CreditScore    Age  Tenure   Balance  NumOfProducts  EstimatedSalary
Retained       651.85  37.41    5.03  72745.30           1.54         99738.39
Churned        645.35  44.84    4.93  91108.54           1.48        101465.68

In [14]:
engagement_churn = (
    df.groupby("EngagementStatus")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

engagement_churn["ChurnRate"] = engagement_churn["mean"] * 100

engagement_churn["ChurnContribution"] = (
    engagement_churn["sum"] / churned_customers * 100
)

engagement_churn = engagement_churn.drop(columns="mean")

engagement_churn

  EngagementStatus  count   sum  ChurnRate  ChurnContribution
0           Active   5151   735  14.269074          36.082474
1         Inactive   4849  1302  26.850897          63.917526

In [15]:
product_churn = (
    df.groupby("NumOfProducts")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

product_churn["ChurnRate"] = product_churn["mean"] * 100

product_churn["ChurnContribution"] = (
    product_churn["sum"] / churned_customers * 100
)

product_churn = product_churn.drop(columns="mean")

product_churn

   NumOfProducts  count   sum   ChurnRate  ChurnContribution
0              1   5084  1409   27.714398          69.170349
1              2   4590   348    7.581699          17.083947
2              3    266   220   82.706767          10.800196
3              4     60    60  100.000000           2.945508

In [16]:
gender_churn = (
    df.groupby("Gender")["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

gender_churn["ChurnRate"] = gender_churn["mean"] * 100

gender_churn["ChurnContribution"] = (
    gender_churn["sum"] / churned_customers * 100
)

gender_churn = gender_churn.drop(columns="mean")

gender_churn

   Gender  count   sum  ChurnRate  ChurnContribution
0  Female   4543  1139  25.071539          55.915562
1    Male   5457   898  16.455928          44.084438

In [17]:
risk_profile = (
    df.groupby(
        ["Geography", "AgeGroup",
         "EngagementStatus", "BalanceSegment"]
    )["Exited"]
    .agg(["count", "sum", "mean"])
    .reset_index()
)

risk_profile["ChurnRate"] = risk_profile["mean"] * 100

risk_profile["ChurnContribution"] = (
    risk_profile["sum"] / churned_customers * 100
)

risk_profile = risk_profile.drop(columns="mean")

risk_profile = risk_profile.sort_values(
    "ChurnRate",
    ascending=False
)

risk_profile.head(15)

,Geography,AgeGroup,EngagementStatus,BalanceSegment,count,sum,ChurnRate,ChurnContribution
15,France,60+,Inactive,High-balance,15,15,100.000000,0.736377
56,Spain,60+,Inactive,Low-balance,4,4,100.000000,0.196367
16,France,60+,Inactive,Low-balance,8,8,100.000000,0.392734
30,Germany,46-60,Inactive,High-balance,237,195,82.278481,9.572901
34,Germany,60+,Inactive,High-balance,26,21,80.769231,1.030928
35,Germany,60+,Inactive,Low-balance,5,4,80.000000,0.196367
57,Spain,60+,Inactive,Zero-balance,9,7,77.777778,0.343643
50,Spain,46-60,Inactive,Low-balance,26,20,76.923077,0.981836
31,Germany,46-60,Inactive,Low-balance,39,28,71.794872,1.374570
55,Spain,60+,Inactive,High-balance,7,5,71.428571,0.245459
10,France,46-60,Inactive,Low-balance,47,31,65.957447,1.521846
49,Spain,46-60,Inactive,High-balance,64,40,62.500000,1.963672
9,France,46-60,Inactive,High-balance,144,87,60.416667,4.270987
17,France,60+,Inactive,Zero-balance,15,9,60.000000,0.441826
11,France,46-60,Inactive,Zero-balance,154,92,59.740260,4.516446

In [18]:
reliable_risk_profiles = (
    risk_profile[
        risk_profile["count"] >= 50
    ]
    .sort_values(
        "ChurnRate",
        ascending=False
    )
)

reliable_risk_profiles.head(15)

,Geography,AgeGroup,EngagementStatus,BalanceSegment,count,sum,ChurnRate,ChurnContribution
30,Germany,46-60,Inactive,High-balance,237,195,82.278481,9.572901
49,Spain,46-60,Inactive,High-balance,64,40,62.500000,1.963672
9,France,46-60,Inactive,High-balance,144,87,60.416667,4.270987
11,France,46-60,Inactive,Zero-balance,154,92,59.740260,4.516446
51,Spain,46-60,Inactive,Zero-balance,76,45,59.210526,2.209131
28,Germany,46-60,Active,High-balance,195,105,53.846154,5.154639
6,France,46-60,Active,High-balance,144,51,35.416667,2.503682
26,Germany,30-45,Inactive,High-balance,616,212,34.415584,10.407462
7,France,46-60,Active,Low-balance,63,21,33.333333,1.030928
44,Spain,30-45,Inactive,Low-balance,93,30,32.258065,1.472754
8,France,46-60,Active,Zero-balance,197,61,30.964467,2.994600
46,Spain,46-60,Active,High-balance,95,27,28.421053,1.325479
32,Germany,60+,Active,High-balance,65,17,26.153846,0.834561
24,Germany,30-45,Active,High-balance,604,134,22.185430,6.578301
38,Germany,<30,Inactive,High-balance,151,32,21.192053,1.570938

In [19]:
geo_age_churn = (
    df.groupby(["Geography", "AgeGroup"])["Exited"]
      .agg(["count", "sum", "mean"])
      .reset_index()
)

geo_age_churn["ChurnRate"] = geo_age_churn["mean"] * 100

geo_age_churn["ChurnContribution"] = (
    geo_age_churn["sum"] / churned_customers * 100
)

geo_age_churn = geo_age_churn.drop(columns="mean")

geo_age_churn = geo_age_churn.sort_values(
    "ChurnRate",
    ascending=False
)

geo_age_churn

   Geography AgeGroup  count  sum  ChurnRate  ChurnContribution
5    Germany    46-60    502  338  67.330677          16.593029
1     France    46-60    749  343  45.794393          16.838488
9      Spain    46-60    396  161  40.656566           7.903780
6    Germany      60+    113   44  38.938053           2.160039
4    Germany    30-45   1522  385  25.295664          18.900344
10     Spain      60+    120   25  20.833333           1.227295
2     France      60+    231   46  19.913420           2.258223
7    Germany      <30    372   47  12.634409           2.307315
8      Spain    30-45   1558  195  12.516046           9.572901
0     France    30-45   3168  376  11.868687          18.458517
11     Spain      <30    403   32   7.940447           1.570938
3     France      <30    866   45   5.196305           2.209131

In [20]:
# 1. Overall Churn Rate
overall_churn_rate = df["Exited"].mean() * 100

# 2. Segment Churn Rate
segment_churn_rate = {
    "Germany": geography_churn.loc[
        geography_churn["Geography"] == "Germany", "ChurnRate"
    ].iloc[0],

    "Age 46-60": age_churn.loc[
        age_churn["AgeGroup"] == "46-60", "ChurnRate"
    ].iloc[0],

    "High-balance": balance_churn.loc[
        balance_churn["BalanceSegment"] == "High-balance", "ChurnRate"
    ].iloc[0]
}

# 3. High-Value Churn Ratio
high_value_customers = (
    df["BalanceSegment"] == "High-balance"
).sum()

high_value_churners = (
    (df["BalanceSegment"] == "High-balance") &
    (df["Exited"] == 1)
).sum()

high_value_churn_ratio = (
    high_value_churners / high_value_customers * 100
)

# 4. Geographic Risk Index
# Germany churn rate relative to overall churn rate
germany_churn_rate = segment_churn_rate["Germany"]

geographic_risk_index = (
    germany_churn_rate / overall_churn_rate
)

# 5. Engagement Drop Indicator
active_churn_rate = engagement_churn.loc[
    engagement_churn["EngagementStatus"] == "Active",
    "ChurnRate"
].iloc[0]

inactive_churn_rate = engagement_churn.loc[
    engagement_churn["EngagementStatus"] == "Inactive",
    "ChurnRate"
].iloc[0]

engagement_drop_indicator = (
    inactive_churn_rate - active_churn_rate
)

kpi_summary = pd.DataFrame({
    "KPI": [
        "Overall Churn Rate",
        "Germany Churn Rate",
        "Age 46-60 Churn Rate",
        "High-balance Churn Rate",
        "High-Value Churn Ratio",
        "Geographic Risk Index",
        "Engagement Drop Indicator"
    ],
    "Value": [
        overall_churn_rate,
        germany_churn_rate,
        segment_churn_rate["Age 46-60"],
        segment_churn_rate["High-balance"],
        high_value_churn_ratio,
        geographic_risk_index,
        engagement_drop_indicator
    ]
})

kpi_summary["Value"] = kpi_summary["Value"].round(2)

kpi_summary

                         KPI  Value
0         Overall Churn Rate  20.37
1         Germany Churn Rate  32.44
2       Age 46-60 Churn Rate  51.12
3    High-balance Churn Rate  24.98
4     High-Value Churn Ratio  24.98
5      Geographic Risk Index   1.59
6  Engagement Drop Indicator  12.58

In [21]:
# Save Churn Analysis tables

geography_churn.to_csv(
    "../outputs/tables/geography_churn_summary.csv",
    index=False
)

age_churn.to_csv(
    "../outputs/tables/age_churn_summary.csv",
    index=False
)

credit_churn.to_csv(
    "../outputs/tables/credit_churn_summary.csv",
    index=False
)

tenure_churn.to_csv(
    "../outputs/tables/tenure_churn_summary.csv",
    index=False
)

balance_churn.to_csv(
    "../outputs/tables/balance_churn_summary.csv",
    index=False
)

engagement_churn.to_csv(
    "../outputs/tables/engagement_churn_summary.csv",
    index=False
)

product_churn.to_csv(
    "../outputs/tables/product_churn_summary.csv",
    index=False
)

gender_churn.to_csv(
    "../outputs/tables/gender_churn_summary.csv",
    index=False
)

geo_age_churn.to_csv(
    "../outputs/tables/geo_age_churn_summary.csv",
    index=False
)

profile_comparison.to_csv(
    "../outputs/tables/profile_comparison.csv"
)

reliable_risk_profiles.to_csv(
    "../outputs/tables/reliable_risk_profiles.csv",
    index=False
)

kpi_summary.to_csv(
    "../outputs/tables/kpi_summary.csv",
    index=False
)

print("✅ All Churn Analysis tables saved successfully!")

✅ All Churn Analysis tables saved successfully!